---

- hosts: all
  become: true
  pre_tasks:

  - name: Installing Updates and Upgrading (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: controller
  become: true
  tasks:

  - name: Installing Horizon (Ubuntu)
    apt:
      name:
          - openstack-dashboard
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
